version: '3.8'

services:
  # PostgreSQL container
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: viatabloid
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - viatabloid-network

  # Your .NET Backend container
  via-tabloid-backend:
    image: via-tabloid-backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: via-tabloid-backend
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - postgres
    networks:
      - viatabloid-network

networks:
  viatabloid-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local